// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHGvl5JBO8q9vW22Bq66D7STapV_bmNac',
    appId: '1:525003342665:web:4156376794b2033d7c1098',
    messagingSenderId: '525003342665',
    projectId: 'spotify-registration',
    authDomain: 'spotify-registration.firebaseapp.com',
    storageBucket: 'spotify-registration.appspot.com',
    measurementId: 'G-1Y2S9T468D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBx1Tb4oJ4HIbyNAEX5Y1K2ss-W3GNkwe4',
    appId: '1:525003342665:android:631ca4f62951b7c67c1098',
    messagingSenderId: '525003342665',
    projectId: 'spotify-registration',
    storageBucket: 'spotify-registration.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAK3AxdRomYaZNaTj2zI16qMzKFOe_ntPE',
    appId: '1:525003342665:ios:7ebf1d196ab1fb2f7c1098',
    messagingSenderId: '525003342665',
    projectId: 'spotify-registration',
    storageBucket: 'spotify-registration.appspot.com',
    androidClientId: '525003342665-49alsi9410uq57343p1j8v1bttnkbk7i.apps.googleusercontent.com',
    iosClientId: '525003342665-15jktvqlnsaao38hlsbv13c4g1gtkp54.apps.googleusercontent.com',
    iosBundleId: 'com.example.spotifyClone',
  );
}
